---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

He thought he saw an Elephant  
That practised on a fife:  
He looked again, and found it was  
A letter from his wife.  
'At length I realize,' he said,  
  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

A Prayer for Rain  
BY LISEL MUELLER  
Let it come down: these thicknesses of air  
have long enough walled love away from love;  
stillness has hardened until words despair  
of their high leaps and kisses shut themselves  
back into wishing. Crippled lovers lie  
against a weather which holds out on them,  
waiting, awaiting some shrill sign, some cry,  
some screaming cat that smells a sacrifice  
and spells them thunder. Start the mumbling lips,  
syllable by monotonous syllable,  
that wash away the sullen griefs of love  
and drown out knowledge of an ancient war—  
o, ill-willed dark, give with the sound of rain,  
let love be brought to ignorance again.  
  
